### ISSUE TITLE
"Nothing to verify against because every test failed" for one error (not fail)

### ISSUE THREAD

**Issue by AlexWayfer** [minitest/minitest-bisect#23]
Hello!

I have a case when sometimes one test has an error, and I want to isolate it, but `minitest-bisect` refuses to do it, because, as I understand, it's error not failure:

```
> env MTB_VERBOSE=2 minitest_bisect test/mixins/test_exec.rb --seed 1030

/home/alex/.rbenv/versions/2.7.0/bin/ruby -Itest:lib -e 'require "./test/mixins/test_exec.rb"' -- --seed 1030 --server 43666

reproducing...Run options: --seed 1030 --server 43666

# Running:

E........................

Finished in 0.179814s, 139.0324 runs/s, 133.4711 assertions/s.

  1) Error:
Toys::StandardMixins::Exec::exit_on_nonzero_status method#test_0004_handles error result object:
RuntimeError: uninitialized constant Toys::Utils::Exec
    /home/alex/Projects/ruby/toys/toys-core/test/mixins/test_exec.rb:357:in `block (3 levels) in <top (required)>'

25 runs, 24 assertions, 0 failures, 1 errors, 0 skips
 in 0.42 sec
Nothing to verify against because every test failed. Aborting.
```

**Comment by zenspider** [comment]
No... this is a wierd one. Error or failure should be fine.

> Nothing to verify against because every test failed. Aborting

that's the odd part. The `Exec` part has me a bit wary... does this test in question do anything exotic?

**Comment by zenspider** [comment]
Ooh... but I can also say, with that seed, it fails first. So it isn't a normal bisection scenario. It isn't really a question about what makes it fail (you can do that with `minitest the_file.rb -n /name-of-test/` and it should fail by itself.

In this case, the real question (and something bisect doesn't do yet) is "why does it ever pass"... Some other test defines or requires something that defines the const you're failing on.

If I had to guess, given the name of the test and the missing const, you need a require at the top of the file that defines `Toys::Utils::Exec`.

**Comment by AlexWayfer** [comment]
> In this case, the real question (and something bisect doesn't do yet) is "why does it ever pass"... Some other test defines or requires something that defines the const you're failing on.

Yes.

If you're interested — this is https://github.com/dazuma/toys repository.

**Comment by zenspider** [comment]
I've changed the output from:

```diff
-    raise "Nothing to verify against because every test failed. Aborting." if
-      culprits.empty? && seen_bad
```

to a combination of outputs:

```diff
+    if normal then
+      raise "Reproduction run passed? Aborting." unless tainted?
+      raise "Verification failed. No culprits? Aborting." if culprits.empty? && seen_bad
+    else
+      raise "Reproduction failed? Not false positive. Aborting." if tainted?
+      raise "Verification failed. No culprits? Aborting." if culprits.empty? || seen_bad
     end
```

and extended minitest-bisect in order to answer the question of "why does it ever pass" by adding an "inverted" (false positive) bisection.

I think this addresses everything we can do with the above scenario. It still will never be great in some edge cases, but at least it might explain them a little better?

Closing as fixed.
